feat: PHPUnit 10.3 support
php-mock/php-mock-phpunit pull request #62
Opened 2023-08-09 19:08 UTC by michalbundyra

2023-10-26 20:31 UTC, marcoscoelho requested changes
however, if the var cannot be changed by ref. it will not make sense to call the implementation.

2023-10-26 20:31 UTC, marcoscoelho commented on classes/DefaultArgumentRemoverReturnTypes100.php
> +            MockFunctionGenerator::removeDefaultArguments($invocation->parameters());
fix only vars can be passed as reference.

```suggestion
            $paramaters = $invocation->parameters();
            MockFunctionGenerator::removeDefaultArguments($paramaters);
```

2023-10-26 20:31 UTC, marcoscoelho commented on classes/DefaultArgumentRemoverReturnTypes100.php
> +            MockFunctionGenerator::removeDefaultArguments($this->parameters());
fix only vars can be passed as reference.

```suggestion
            $paramaters = $this->parameters();
            MockFunctionGenerator::removeDefaultArguments($paramaters);
```

2023-10-27 22:02 UTC, michalbundyra commented
Closing in favour of #63

2023-10-27 22:02 UTC, closed without merging